sudo: false

os:
  - osx
  - linux

#language: python

#addons:
#  apt:
#    packages:
#      - gfortran
#      - libatlas-dev
#      - libatlas-base-dev
#      - liblapack-dev

cache:
  directories:
     - $HOME/download/
     - $HOME/install/

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.5

before_install:
  - export CONDA_CACHED=1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export OS=Linux;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS=MacOSX;
    else
      echo "OS not supported yet";
      exit 1;
    fi;
  - if [[ $PYTHON_VERSION == "2.7" ]]; then
      export MINICONDA=Miniconda;
    elif [[ $PYTHON_VERSION == 3* ]]; then
      export MINICONDA=Miniconda3;
    else
      echo "Could not find python version";
      exit 1;
    fi;
  - if [ ! -d $HOME/download/ ]; then mkdir $HOME/download/; fi;
  - if [ ! -d $HOME/install/ ]; then mkdir $HOME/install/; fi;
  - export MINICONDA_FILE=$MINICONDA-latest-$OS-x86_64-$PYTHON_VERSION
  - export MINCONDA_CACHE_FILE=$HOME/download/$MINICONDA_FILE.sh
  - export MINICONDA_INSTALL=$HOME/install/$MINICONDA_FILE
  - if [ ! -f $MINCONDA_CACHE_FILE ]; then
      export CONDA_CACHED=0;
      wget http://repo.continuum.io/miniconda/$MINICONDA-latest-$OS-x86_64.sh -O $MINCONDA_CACHE_FILE;
      bash $MINCONDA_CACHE_FILE -b -p $MINICONDA_INSTALL;
    fi;
  - export PATH="$MINICONDA_INSTALL/bin:$PATH";
  
install:
  - conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six matplotlib;
  - pip install codecov
  - python setup.py develop
   
script:
  - coverage run travis_tests.py

after_success:
  - codecov