sudo: false

os:
  - linux
  - osx

language: python

#addons:
#  apt:
#    packages:
#      - gfortran
#      - libatlas-dev
#      - libatlas-base-dev
#      - liblapack-dev

python:
  - 2.7
  - 3.3
  - 3.4

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
#  - conda update --yes conda
  
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six
  - pip install .

script:
  - cd $HOME
  - mkdir empty
  - cd empty
  - nosetests GPy.testing

cache:
  directories:
    - $HOME/.cache/pip
