language: python
python:
  - "2.7"

#Set virtual env with system-site-packages to true
virtualenv:
  system_site_packages: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - sudo apt-get install -qq python-scipy python-pip
  - sudo apt-get install -qq python-matplotlib
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - pip install --upgrade numpy==1.7.1
  - pip install sphinx
  - pip install nose
  - pip install . --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  - nosetests GPy/testing
