sudo: false

os:
- osx
- linux

addons:
  apt_packages:
    - pandoc

#cache:
#  directories:
#  - "$HOME/download/"
#  - "$HOME/install/"

env:
  - PYTHON_VERSION=2.7
  #- PYTHON_VERSION=3.3
  #- PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  #- PYTHON_VERSION=3.7

before_install:
- wget https://github.com/mzwiessele/travis_scripts/raw/master/download_miniconda.sh
- wget https://github.com/mzwiessele/travis_scripts/raw/master/install_retry.sh
- source download_miniconda.sh
- echo $PATH

install:
- echo $PATH
- source install_retry.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];
  then
    conda install --yes pandoc;
  fi;
- pip install codecov
- pip install coveralls
- pip install pypandoc
- pip install git+git://github.com/BRML/climin.git
- pip install autograd
- pip install nose-show-skipped
- python setup.py develop

script:
  - coverage run travis_tests.py

after_success:
  - codecov
  - coveralls

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      export DIST='sdist';
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
      export DIST='bdist_wheel';
    fi;

deploy:
  provider: pypi
  user: maxz
  password:
    secure: "vMEOlP7DQhFJ7hQAKtKC5hrJXFl5BkUt4nXdosWWiw//Kg8E+PPLg88XPI2gqIosir9wwgtbSBBbbwCxkM6uxRNMpoNR8Ixyv9fmSXp4rLl7bbBY768W7IRXKIBjpuEy2brQjoT+CwDDSzUkckHvuUjJDNRvUv8ab4P/qYO1LG4="
  on:
    branch: deploy
  edge:
    branch: v1.8.45
  distributions: $DIST
  skip_existing: true
  skip_cleanup: true
  skip_upload_docs: false
